// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxdkseuxpkydwqclhgeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4ZGtzZXV4cGt5ZHdxY2xoZ2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjU1NDEsImV4cCI6MjA3MDA0MTU0MX0.bbmelKFsdQ_vI4JG6ZvmGNwveD79HcZASjJE-T8-PA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});